### ISSUE TITLE
Badge purchased but not awarded

### ISSUE THREAD

**Issue by cxplay** [toastr-space/issue-tracker#1]
I purchased two badges, but they don't seem to have been actually awarded, you can check the invoice for:
1. <https://btcpay.btcandfriends.com/i/W1tgiCdHEadr2kkAqqK9nW/receipt>
2. <https://btcpay.btcandfriends.com/i/532FWXwv8iqmV3pkbrNATp/receipt>

**Comment by satoshisound** [comment]
It looks like our server is not able to write to any of the Nostr relays we had it set to use. I will look into this and get back to you. Thanks for the bug report.

**Comment by satoshisound** [comment]
@cxplay please try again. GitHub and Twitter badges should both work now. And I'd be happy to refund the 20 sats if you provide a ln address or invoice. My npub is: npub1sy70twa0vadtk8hjs6wt2hmfszduj04tw78ccs3ktmr9u99mfmqsj62srx

**Comment by cxplay** [comment]
> @cxplay please try again. GitHub and Twitter badges should both work now. And I'd be happy to refund the 20 sats if you provide a ln address or invoice. My npub is: npub1sy70twa0vadtk8hjs6wt2hmfszduj04tw78ccs3ktmr9u99mfmqsj62srx

Cool! I will contact you with Nostr!
